### ISSUE TITLE
Just a small suggestion

### ISSUE THREAD

**Issue by Nash-dc** [Multiverse-Framework/Multiverse#14]
Hi Mr.Hoang,
I open this issue because I have a small suggestion.
I checked your wonderful tutorials and already learned a lot.Thanks for your contribute!!
But in this MuJoCo tutoiral I found that the font style in the first line of code block `Create a tutorial workspace`is a little weird,check the following picture.This can make reading difficult.The followed code block also have the same problem.
![Screenshot from 2023-09-16 21-58-20](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/fcef2fbf-85ef-438d-8c35-e2dd4b9677c3)

**Comment by HoangGiang93** [comment]
Because you're not supposed to read it like that. It's a Jupyter notebook which you can execute codes directly in the browser. Just open terminal and execute `jupyter-notebook <path/to/MuJoCo-Tutorial.ipynb>`
The result should look like this:
![image](https://github.com/Multiverse-Framework/Multiverse/assets/64316740/00208614-c30d-482e-8ad3-662874dbe8f2)

Btw, please call me Giang, Hoang is my middle name :)

**Comment by Nash-dc** [comment]
I know how to do this,thank you Mr.Giang!

**Comment by HoangGiang93** [comment]
Now I see what you meant. Maybe the code block with bash kernel has some problem. Anyway there will be more comprehensive tutorials. I will take a look to see if it could be fixed.
